export const employeeDepList = [
  "Finance",
  "Sales",
  "Business administration",
  "Customer service",
  "Design",
  "Communications",
  "Human resources",
  "Operations management",
  "IT",
  "Marketing",
  "Project department",
  "Security",
  "Legal department",
];

export const employeePosList = [
  "Chief executive officer",
  "Chief financial officer",
  "Chief information officer",
  "Chief marketing officer",
  "Chief operations officer",
  "Human resources manager",
  "Information technology manager",
  "Marketing manager",
  "Product manager",
  "Sales manager",
  "Administrative assistant",
  "Business analyst",
  "Sales representative",
  "Software engineer",
  "Financial analyst",
  "IT support specialist",
  "Systems administrator",
  "HR Recruiter",
];
